# Generated by Django 2.0.6 on 2018-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1money', models.PositiveIntegerField(default=100000)),
                ('player2money', models.PositiveIntegerField(default=100000)),
                ('bankerMoney', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
