# Generated by Django 2.0.6 on 2018-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indian', '0002_auto_20180606_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1money', models.PositiveIntegerField(default=100000)),
                ('player1CardNumber', models.PositiveIntegerField()),
                ('player2money', models.PositiveIntegerField(default=100000)),
                ('player2CardNumber', models.PositiveIntegerField()),
                ('bankerMoney', models.PositiveIntegerField(default=0)),
                ('regame', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
