# Generated by Django 2.0.6 on 2018-06-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indian', '0003_auto_20180606_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameset',
            name='bankerMoney',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='player1CardNumber',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='player1money',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='player2CardNumber',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='player2money',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='regame',
        ),
    ]
