# Generated by Django 2.0.6 on 2018-06-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indian', '0004_auto_20180606_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='player_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
